apiVersion: v1
kind: Service
metadata:
  name: demo-service2
  namespace: cl-test
  labels:
    app: demo-label
spec:
  type: NodePort
  ports:
    - port: 1001
      targetPort: 1001
      protocol: TCP
      name: http
      nodePort: 30000
  selector:
    app: demo-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: cl-test
spec:
  selector:
    matchLabels:
      app: demo-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-pod
    spec:
      containers:
        - name: demo-container
          image: ckhero/go-test:v1  #本地私有镜像库的镜像名称+版本
          ports:
            - containerPort: 1001